### ISSUE TITLE
Edge also supports Brotli

### ISSUE THREAD

**Issue by meowsus** [hansottowirtz/sprockets-exporters#1]
"With Firefox, Chrome and Opera now supporting Brotli, this tutorial will explain how to make use of it with Rails."

on https://github.com/hansottowirtz/sprockets-exporters_pack/wiki/How-to-enable-Brotli-with-Rails-and%C2%A0Nginx

should include Edge as well, as per: https://blogs.windows.com/msedgedev/2016/12/20/introducing-brotli-compression/

**Comment by hansottowirtz** [comment]
Fixed, thanks.
